### ISSUE TITLE
Find non-visual version of diffPrint to collect differences in lyrics

### ISSUE THREAD

**Issue by sastoudt** [the-pudding/kidz-bop-data#4]
I originally used [this](https://cran.r-project.org/web/packages/diffobj/diffobj.pdf) package to do the visual comparison of lyrics, but we'll need something that returns a list of differences instead of just displaying them visually. 

Maybe something like [this](https://stackoverflow.com/questions/28834459/extract-characters-that-differ-between-two-strings) or go back to basics with something like [this](https://unix.stackexchange.com/questions/428419/how-to-write-the-difference-between-two-files-into-a-file).

**Comment by sastoudt** [comment]
Example:

- [Original](https://github.com/the-pudding/kidz-bop-data/blob/master/tests/test.txt)
- [Kidz Bop](https://github.com/the-pudding/kidz-bop-data/blob/master/tests/test2.txt)
- [Difference](https://github.com/the-pudding/kidz-bop-data/blob/master/tests/testC.txt)

Can we just take any word preceded with a minus sign in the difference file as a "censored" word?

**Comment by jadiehm** [comment]
I think this approach with the minus signs makes sense. First step is to know if there is a difference or not and flag that for us to take a look. I think there's probably a programmatic go-between too were we can automatically code some things: words like "beer" get tagged "alcohol" and small articles like "the" get thrown out so we we don't have to have manual eyes on every single difference.

**Comment by sastoudt** [comment]
We could also do setdiff(words_in_original, words_in_kidzbop) to find words that are skipped in the kidzbop versions.

**Comment by jadiehm** [comment]
I'm open to whatever you're most comfortable with that will get us the results we need. :)

**Comment by sastoudt** [comment]
First pass: [this](https://github.com/the-pudding/kidz-bop-data/blob/master/data/censoring/setdiffWords.csv) lists every word that was in original song but not in Kidz Bop. The problem is phrases are changed, making a lot of innocuous words show up as "censored."  This leads to A TON of words to sift through to manually group and will make things hard to back calculate what words weren't censored before but are now. I'm going to try the line by line plus/minus approach and see if that helps with phrases.

**Comment by sastoudt** [comment]
This isn't perfect, but I narrowed censored words down to [censored phrases](https://github.com/the-pudding/kidz-bop-data/blob/master/data/censoring/setdiffPhrases.csv). Now this is a little over 6000 phrases to manually check/classify which feels more manageable.

**Comment by sastoudt** [comment]
We more or less have this under control now, closing to clean up and see what is left.
